export const COLLEGESDATA = [
  {
    id: 1,
    name: "Harvard University",
    city: "Cambridge",
    state: "MA",
    country: "USA",
    no_of_students: 20000,
    courses: ["Computer Science", "Law", "Business", "Medicine", "Engineering"],
    website: "https://www.harvard.edu",
  },
  {
    id: 2,
    name: "Stanford University",
    city: "Stanford",
    state: "CA",
    country: "USA",
    no_of_students: 17000,
    courses: ["Computer Science", "Engineering", "Business", "Law", "Medicine"],
    website: "https://www.stanford.edu",
  },
  {
    id: 3,
    name: "Massachusetts Institute of Technology (MIT)",
    city: "Cambridge",
    state: "MA",
    country: "USA",
    no_of_students: 11500,
    courses: [
      "Computer Science",
      "Engineering",
      "Physics",
      "Mathematics",
      "Biology",
    ],
    website: "https://www.mit.edu",
  },
  {
    id: 4,
    name: "University of California, Berkeley (UC Berkeley)",
    city: "Berkeley",
    state: "CA",
    country: "USA",
    no_of_students: 42000,
    courses: [
      "Computer Science",
      "Business",
      "Engineering",
      "Political Science",
      "Economics",
    ],
    website: "https://www.berkeley.edu",
  },
  {
    id: 5,
    name: "Columbia University",
    city: "New York",
    state: "NY",
    country: "USA",
    no_of_students: 31000,
    courses: ["Law", "Business", "Engineering", "Medicine", "Journalism"],
    website: "https://www.columbia.edu",
  },
  {
    id: 6,
    name: "University of Chicago",
    city: "Chicago",
    state: "IL",
    country: "USA",
    no_of_students: 17000,
    courses: [
      "Economics",
      "Political Science",
      "Mathematics",
      "Law",
      "Physics",
    ],
    website: "https://www.uchicago.edu",
  },
  {
    id: 7,
    name: "Princeton University",
    city: "Princeton",
    state: "NJ",
    country: "USA",
    no_of_students: 8300,
    courses: [
      "Public Policy",
      "Mathematics",
      "Physics",
      "Engineering",
      "Computer Science",
    ],
    website: "https://www.princeton.edu",
  },
  {
    id: 8,
    name: "Yale University",
    city: "New Haven",
    state: "CT",
    country: "USA",
    no_of_students: 14000,
    courses: ["Law", "Political Science", "Medicine", "History", "Economics"],
    website: "https://www.yale.edu",
  },
  {
    id: 9,
    name: "California Institute of Technology (Caltech)",
    city: "Pasadena",
    state: "CA",
    country: "USA",
    no_of_students: 2200,
    courses: [
      "Engineering",
      "Physics",
      "Mathematics",
      "Computer Science",
      "Biology",
    ],
    website: "https://www.caltech.edu",
  },
  {
    id: 10,
    name: "University of Michigan",
    city: "Ann Arbor",
    state: "MI",
    country: "USA",
    no_of_students: 46000,
    courses: ["Engineering", "Business", "Medicine", "Law", "Computer Science"],
    website: "https://www.umich.edu",
  },
];


